In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("C:\\Users\\rohan\\EDA_Practice\\food-price-index-september-2023-index-numbers.csv")

In [4]:
df

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1
0,CPIM.SE901,1960.01,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
...,...,...,...,...,...,...,...,...
12863,CPIM.SE901502,2023.05,1347.000000,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food
12864,CPIM.SE901502,2023.06,1361.000000,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food
12865,CPIM.SE901502,2023.07,1366.000000,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food
12866,CPIM.SE901502,2023.08,1367.000000,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food
12867,CPIM.SE901502,2023.09,1370.000000,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food

In [6]:
df.drop('STATUS',axis=1)     # by remove column from data 
                        # if axis=1 consider as column and axis =0 then consider as row other wise , if we not given then by default consider as row

,Series_reference,Period,Data_value,UNITS,Subject,Group,Series_title_1
0,CPIM.SE901,1960.01,45.923461,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
1,CPIM.SE901,1960.02,45.498637,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
2,CPIM.SE901,1960.03,45.116296,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
3,CPIM.SE901,1960.04,45.158779,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
4,CPIM.SE901,1960.05,45.286226,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
...,...,...,...,...,...,...,...
12863,CPIM.SE901502,2023.05,1347.000000,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food
12864,CPIM.SE901502,2023.06,1361.000000,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food
12865,CPIM.SE901502,2023.07,1366.000000,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food
12866,CPIM.SE901502,2023.08,1367.000000,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food
12867,CPIM.SE901502,2023.09,1370.000000,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food

In [8]:
df  # SATATUS colun is remove

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1
0,CPIM.SE901,1960.01,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index for New Zealand,Food
...,...,...,...,...,...,...,...,...
12863,CPIM.SE901502,2023.05,1347.000000,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food
12864,CPIM.SE901502,2023.06,1361.000000,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food
12865,CPIM.SE901502,2023.07,1366.000000,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food
12866,CPIM.SE901502,2023.08,1367.000000,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food
12867,CPIM.SE901502,2023.09,1370.000000,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Ready-to-eat food

In [ ]:
df.drop(columns=['Subject','Group'],inplace=True) # delete more than 2 at time using this commond and if we given columns then no need to declare axis

In [15]:
df

      Series_reference   Period   Data_value STATUS  UNITS     Series_title_1
0           CPIM.SE901  1960.01    45.923461  FINAL  Index               Food
1           CPIM.SE901  1960.02    45.498637  FINAL  Index               Food
2           CPIM.SE901  1960.03    45.116296  FINAL  Index               Food
3           CPIM.SE901  1960.04    45.158779  FINAL  Index               Food
4           CPIM.SE901  1960.05    45.286226  FINAL  Index               Food
...                ...      ...          ...    ...    ...                ...
12863    CPIM.SE901502  2023.05  1347.000000  FINAL  Index  Ready-to-eat food
12864    CPIM.SE901502  2023.06  1361.000000  FINAL  Index  Ready-to-eat food
12865    CPIM.SE901502  2023.07  1366.000000  FINAL  Index  Ready-to-eat food
12866    CPIM.SE901502  2023.08  1367.000000  FINAL  Index  Ready-to-eat food
12867    CPIM.SE901502  2023.09  1370.000000  FINAL  Index  Ready-to-eat food

[12868 rows x 6 columns]

In [16]:
df.isnull().sum()  # from this command we can find how many null value present in our data for specific column

Series_reference    0
Period              0
Data_value          3
STATUS              0
UNITS               0
Series_title_1      0
dtype: int64

In [18]:
df.duplicated()   # if you want check duplicated value

0        False
1        False
2        False
3        False
4        False
         ...
12863    False
12864    False
12865    False
12866    False
12867    False
Length: 12868, dtype: bool

In [19]:
# Group By

In [22]:
obj = df.groupby('Series_reference')  # object created for group

In [23]:
obj

In [25]:
obj.get_group('CPIM.SE901')   # perticular type

    Series_reference   Period   Data_value STATUS  UNITS Series_title_1
0         CPIM.SE901  1960.01    45.923461  FINAL  Index           Food
1         CPIM.SE901  1960.02    45.498637  FINAL  Index           Food
2         CPIM.SE901  1960.03    45.116296  FINAL  Index           Food
3         CPIM.SE901  1960.04    45.158779  FINAL  Index           Food
4         CPIM.SE901  1960.05    45.286226  FINAL  Index           Food
..               ...      ...          ...    ...    ...            ...
760       CPIM.SE901  2023.05  1271.000000  FINAL  Index           Food
761       CPIM.SE901  2023.06  1291.000000  FINAL  Index           Food
762       CPIM.SE901  2023.07  1284.000000  FINAL  Index           Food
763       CPIM.SE901  2023.08  1290.000000  FINAL  Index           Food
764       CPIM.SE901  2023.09  1285.000000  FINAL  Index           Food

[765 rows x 6 columns]

In [26]:
# in real time huge amount of data given , for work perticular group data so groupby is imp roll